-- run-tests.lua -- test suite for dcrgraph (run from the repository root):
--
--   texlua tests/run-tests.lua            run all tests
--   texlua tests/run-tests.lua --update   accept the current converter output
--                                         as the new expected output
--
-- 1. Content: for every xml/*.xml, what the graph says (events, labels,
--    roles, types, marking, nesting, relations) -- without any positions --
--    compared with tests/expected/content/<name>.txt.
--    Layout: where it is drawn (box positions and sizes, nesting areas,
--    relation routes) compared with tests/expected/layout/<name>.txt.
--    A moved box only fails the layout test; a changed relation only the
--    content test.
-- 2. Gallery: tests/xml-gallery.tex (generated: every xml/*.xml via
--    \includedcrgraph, with and without waypoints) must compile with LuaLaTeX.
-- 3. Examples: the example documents must compile (twice) with pdfLaTeX and
--    LuaLaTeX (dcrjs-example.tex: LuaLaTeX only).
-- Look at tests/out/xml-gallery.pdf to check the pictures themselves.
kpse.set_program_name("luatex")

local update = arg[1] == "--update"
local OUT = "tests/out"
local EXPECTED = "tests/expected"
lfs.mkdir(OUT)
lfs.mkdir(EXPECTED)
lfs.mkdir(EXPECTED .. "/content")
lfs.mkdir(EXPECTED .. "/layout")

-- the converter, loaded from dcrgraph.sty as in dcrgraph-cli.lua
local f = assert(io.open("dcrgraph.sty", "rb"), "run from the repository root")
local text = f:read("*a")
f:close()
local s = assert(text:find("-- DCRGRAPHS " .. "LUA BEGIN", 1, true))
local _, nl = text:sub(1, s):gsub("\n", "")
local dcrgraphs = assert(load(string.rep("\n", nl) .. text:sub(s), "@dcrgraph.sty"))()

local failures, passed = {}, 0
local function ok(name) passed = passed + 1; print("  ok    " .. name) end
local function bad(name, why)
  failures[#failures + 1] = name
  print("  FAIL  " .. name .. (why and ("  (" .. why .. ")") or ""))
end

local function readfile(name)
  local h = io.open(name, "rb")
  if not h then return nil end
  local t = h:read("*a"); h:close()
  return (t:gsub("\r\n", "\n"))
end
local function writefile(name, t)
  local h = assert(io.open(name, "wb")); h:write(t); h:close()
end

-- xml/*.xml, sorted
local xmls = {}
for name in lfs.dir("xml") do
  if name:match("%.xml$") then xmls[#xmls + 1] = name end
end
table.sort(xmls)

-- compare lines with tests/expected/<kind>/<name>.txt; on a difference,
-- report the first differing line
local function check(kind, name, lines)
  local label = kind .. " " .. name
  local got = table.concat(lines, "\n") .. "\n"
  local expfile = EXPECTED .. "/" .. kind .. "/" .. name .. ".txt"
  local expected = readfile(expfile)
  if update or not expected then
    writefile(expfile, got)
    print("  saved " .. label .. (expected and "" or "  (new)"))
  elseif got == expected then
    ok(label)
  else
    local outfile = OUT .. "/" .. kind .. "-" .. name .. ".txt"
    writefile(outfile, got)
    local exp = {}
    for l in expected:gmatch("[^\n]+") do exp[#exp + 1] = l end
    local i = 1
    while lines[i] and lines[i] == exp[i] do i = i + 1 end
    bad(label, "line " .. i .. ": expected `" .. tostring(exp[i]) ..
      "', got `" .. tostring(lines[i]) .. "' -- full output in " .. outfile)
  end
end

-- 1. content and layout ------------------------------------------------
print("Content and layout (" .. #xmls .. " files):")
for _, x in ipairs(xmls) do
  local name = x:gsub("%.xml$", ""):gsub("[^%w%-]", "-")
  local good, graph, opts = pcall(dcrgraphs.read, "xml/" .. x, "")
  if not good then
    bad(name, tostring(graph))
  else
    check("content", name, dcrgraphs.describe_content(graph))
    check("layout", name, dcrgraphs.describe_layout(graph, opts))
  end
end

-- 2 and 3. compiling ----------------------------------------------------
local function compile(engine, file, jobname)
  local cmd = string.format(
    '%s -interaction=nonstopmode -halt-on-error -output-directory=%s -jobname=%s "%s"',
    engine, OUT, jobname, file)
  local quiet = (os.type == "windows") and " >NUL 2>&1" or " >/dev/null 2>&1"
  local r
  for _ = 1, 2 do r = os.execute(cmd .. quiet) end   -- twice: parallel relations
  return r == 0 or r == true
end

-- the gallery document: every XML file, plain and with waypoints
local g = { "% generated by tests/run-tests.lua",
  "\\documentclass{article}",
  "\\usepackage[a4paper, margin=1cm, landscape]{geometry}",
  "\\usepackage[T1]{fontenc}", "\\usepackage[scaled=0.92]{helvet}",
  "\\usepackage{dcrgraph}", "\\begin{document}" }
for _, x in ipairs(xmls) do
  for _, o in ipairs({ "", "waypoints" }) do
    g[#g + 1] = "\\begin{figure}[p]\\centering"
    g[#g + 1] = "  \\resizebox{\\ifdim\\width>\\linewidth\\linewidth\\else\\width\\fi}{!}{%"
    g[#g + 1] = "    \\includedcrgraph[" .. o .. "]{xml/" .. x .. "}}"
    g[#g + 1] = "  \\caption{\\texttt{" .. x:gsub("_", "\\_") .. "}" ..
      (o ~= "" and " (" .. o .. ")" or "") .. "}"
    g[#g + 1] = "\\end{figure}"
  end
end
g[#g + 1] = "\\end{document}"
writefile("tests/xml-gallery.tex", table.concat(g, "\n") .. "\n")

print("Gallery:")
if compile("lualatex", "tests/xml-gallery.tex", "xml-gallery") then
  ok("xml-gallery (LuaLaTeX)")
else
  bad("xml-gallery (LuaLaTeX)", "see " .. OUT .. "/xml-gallery.log")
end

print("Examples:")
local examples = {
  { "notation-example.tex", { "pdflatex", "lualatex" } },
  { "logik-eksempel.tex",   { "pdflatex", "lualatex" } },
  { "dcrjs-example.tex",    { "lualatex" } },
}
for _, e in ipairs(examples) do
  for _, engine in ipairs(e[2]) do
    local job = e[1]:gsub("%.tex$", "") .. "-" .. engine
    if compile(engine, e[1], job) then ok(job)
    else bad(job, "see " .. OUT .. "/" .. job .. ".log") end
  end
end

print(string.format("\n%d passed, %d failed", passed, #failures))
os.exit(#failures == 0 and 0 or 1)
